Uploaded first-fourth homework
alexEzhkin/FileManager pull request #1
Opened 2022-06-12 23:18 UTC by alexEzhkin

2022-06-13 15:00 UTC, darya-gurinovich requested changes
Good work! Please, deal with your picker code for camera and we're good to go

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/Cells/CollectionViewCells/CustomCollectionViewCell.swift
> +
Please, leave one empty line max

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/Cells/CollectionViewCells/CustomCollectionViewCell.swift
> +        print(self.cellImageView.image)
Do you need this `print`?

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/Cells/CollectionViewCells/CustomCollectionViewCell.swift
> +class CustomCollectionViewCell: UICollectionViewCell {
Please, try to optimise your cell layout because your label is cut off on iPhone13

![Simulator Screen Shot - iPhone 13 - 2022-06-13 at 17 42 57](https://user-images.githubusercontent.com/25828050/173379691-2fd8d17b-7b16-4227-a22f-a18e5b1de810.png)

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/Cells/TableViewCells/CustomTableViewCell.swift
> +
1 empty line max

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/FilesViewController+TableView.swift
> +    }
Please. add an empty line between functions

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/FilesViewController.swift
> +//        setUpNavigationBar()
Please, remove comments if you don't use them

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/FilesViewController.swift
> +        }
It's better to create an enum that stores the current display mode and save it to the UserDefaults. 

It's not a good idea to save `SelectedSegmentIndex` because if you change a design your code will break. You can store an array with possible display modes. Set segmentControl values and selected index programatically from this array.

It's a good idea to create a `UserDefaultsKey` enum instead of using plain `String`

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/FilesViewController.swift
> +        }
You can drop passing the action to `UIAlertAction`, it's an optional parameter

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/FilesViewController.swift
> +        if (picker.sourceType == UIImagePickerController.SourceType.camera) {
No need for `()` here

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/FilesViewController.swift
> +            let documentDirectory = NSTemporaryDirectory()
You should use your `manager.currentDirectory` here

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/FilesViewController.swift
> +            let data = selectedImage.jpegData(compressionQuality: 0.3)! as NSData
Please, don't use force-unwrap

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/FilesViewController.swift
> +            let photoURL = URL.init(fileURLWithPath: localPath)
Where do you use this variable?

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/FilesViewController.swift
> +        var selectedImage: UIImage!
It's a bad idea to use `!` here. What happens if your source type is `camera`? There's no images if it's this source

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/FilesViewController.swift
> +            manager.createImage(selectedImage, name: imgName + ".jpeg")
Why do you use both `data.write(toFile: localPath, atomically: true)` and `manager.createImage(selectedImage, name: imgName + ".jpeg")`? You should work only with your `manager` when you write something to FileManager

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/FilesViewController.swift
> +            manager.createImage(selectedImage, name: imgName + ".jpeg")
Have you checked this code? I'm not sure it'll work

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/ImageViewController.swift
> +
1 line

2022-06-13 15:00 UTC, darya-gurinovich commented on FileManager/ViewControllers/ImageViewController.swift
> +    }
Do you need this function?

2022-06-14 20:38 UTC, alexEzhkin commented on FileManager/Cells/CollectionViewCells/CustomCollectionViewCell.swift
> +
Resolved.)

2022-06-14 20:38 UTC, alexEzhkin commented on FileManager/Cells/CollectionViewCells/CustomCollectionViewCell.swift
> +        print(self.cellImageView.image)
Nope.) Resolved.)

2022-06-14 20:38 UTC, alexEzhkin commented on FileManager/Cells/TableViewCells/CustomTableViewCell.swift
> +
Resolved.)

2022-06-14 20:39 UTC, alexEzhkin commented on FileManager/ViewControllers/FilesViewController+TableView.swift
> +    }
Added.)

2022-06-14 20:42 UTC, alexEzhkin commented on FileManager/ViewControllers/FilesViewController.swift
> +//        setUpNavigationBar()
Removed.)

2022-06-14 20:44 UTC, alexEzhkin commented on FileManager/ViewControllers/FilesViewController.swift
> +        }
Removed.)

2022-06-14 20:45 UTC, alexEzhkin commented on FileManager/ViewControllers/FilesViewController.swift
> +        if (picker.sourceType == UIImagePickerController.SourceType.camera) {
Removed.)

2022-06-14 20:49 UTC, alexEzhkin commented on FileManager/ViewControllers/FilesViewController.swift
> +            let photoURL = URL.init(fileURLWithPath: localPath)
Sorry, it's from previous realisation.) Removed.)

2022-06-14 20:50 UTC, alexEzhkin commented on FileManager/ViewControllers/ImageViewController.swift
> +
Resolved.)

2022-06-14 20:51 UTC, alexEzhkin commented on FileManager/ViewControllers/ImageViewController.swift
> +    }
Nope.) This function only for test zooming.)
Removed.)

2022-06-14 21:05 UTC, alexEzhkin commented on FileManager/ViewControllers/FilesViewController.swift
> +            manager.createImage(selectedImage, name: imgName + ".jpeg")
Resolved.)

2022-06-14 21:07 UTC, alexEzhkin commented on FileManager/ViewControllers/FilesViewController.swift
> +        var selectedImage: UIImage!
Resolved.)

2022-06-14 21:10 UTC, alexEzhkin commented on FileManager/ViewControllers/FilesViewController.swift
> +            let data = selectedImage.jpegData(compressionQuality: 0.3)! as NSData
Resolved.)

2022-06-14 21:25 UTC, alexEzhkin commented on FileManager/Cells/CollectionViewCells/CustomCollectionViewCell.swift
> +class CustomCollectionViewCell: UICollectionViewCell {
Fixed.)

2022-06-19 21:12 UTC, dashaGurinovich commented on FileManager/Cells/TableViewCells/CustomTableViewCell.swift
> +
You can remove this empty line

2022-06-19 21:12 UTC, dashaGurinovich commented on FileManager/Cells/TableViewCells/CustomTableViewCell.swift
> +    }
If you don't do anything in this function, you can remove it

2022-06-19 21:12 UTC, dashaGurinovich commented on FileManager/Models/ElementsManager.swift
> +            let type: ElementType = name.contains(".png") || name.contains(".jpeg") ? .image : .folder
I saw that you've added `imagesExtensions` array but you don't use it here

2022-06-19 21:12 UTC, dashaGurinovich commented on FileManager/Models/ElementsManager.swift
> +        print(selectedElements)
It's not a good practice to leave `print` in the code. If you don't need it anymore, please remove it

2022-06-19 21:12 UTC, dashaGurinovich commented on FileManager/ViewControllers/FilesViewController.swift
> +        }
@alexEzhkin This comment isn't addressed

2022-06-19 21:13 UTC, dashaGurinovich approved these changes
Good work! Please, fix my comments before you merge

2022-06-20 16:20 UTC, alexEzhkin commented on FileManager/Cells/TableViewCells/CustomTableViewCell.swift
> +
if I remove this line, then in the working mode we will have cells highlighted

2022-06-22 23:59 UTC, merged